services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=codecake'
      - 'POSTGRES_DB=codecake'
      - 'POSTGRES_PASSWORD=2790'
    volumes:
      - 'C:/Users/NAM/volumes/codecake/postgres:/var/lib/postgresql/data'

